class_name ItemData
extends Resource
## Static definition for any item that can exist in the game world.
## JSON source schema and field constraints:
## | Key              | Type   | Constraints / Notes                          |
## |------------------|--------|----------------------------------------------|
## | `id`             | string | Non-empty, unique across all items           |
## | `type`           | string | One of: Type enum values                     |
## | `ui_name`        | string | Non-empty, max 12 characters                 |
## | `description`    | string | Non-empty, max 50 characters                 |
## | `inventory_size` | object | `{ width:int, height:int }`, each dim 1–6    |
## | `buy_price`      | int    | 0–999999. `0` = not buyable                  |
## | `sell_price`     | int    | 0–999999. `0` = not sellable                 |
## | `stack_size`     | int    | 1–999. `1` = not stackable                   |
## | `availability`   | int    | 1–4. Earliest chapter in merchant shop.      |
## |                  |        | Ignored when `buy_price == 0`; generator     |
## |                  |        | writes `AVAILABILITY_NOT_FOR_SALE` instead.  |
## | `ammo_type`      | string | AmmoType; only when `type == WEAPON`         |
##
## Bounds for all numeric fields are in [ItemSchema].
## See: "res://docs/decisions/item_architecture.md"
##
## [b]No validation is performed on this class's fields.[/b] [code]ItemData[/code] is a
## plain data holder — validation is the responsibility of the pipeline that produces it:
## [br]- [code]generate_item_resources.gd[/code] validates every JSON entry before writing
##   any [code].tres[/code] file.
## [br]- [code]ItemRegistry[/code] guards against missing or malformed resources at load time.
## [br]- [code]PlayerInventory[/code] enforces business rules at placement time
##   (stack bounds via [constant ItemSchema.MIN_STACK] and [member stack_size]).

## Type determines item behaviour and gameplay role.
enum Type {
	## E.g. First Aid Spray.
	MED,
	## E.g. Red Herb.
	COMBINABLE_MED,
	## E.g. TMP Ammo.
	AMMO,
	## E.g. Attache Case S. (Inventory size upgrades)
	INVENTORY_UPGRADE,
	## E.g. Rifle
	WEAPON,
	## E.g. Ammo Capacity Upgrade
	WEAPON_UPGRADE,
	## E.g. Green Catseye
	TREASURE,
	## E.g. Emblem (Left half)
	KEY,
}

## Ammo type a weapon consumes. Only meaningful when [member type] is [constant Type.WEAPON].
enum AmmoType {
	## No ammo (not a weapon or weapon does not use ammo).
	NONE,
	## Handgun ammunition.
	HANDGUN_AMMO,
	## Submachine gun ammunition.
	SMG_AMMO,
}

## [@export] is required for Godot to serialize these properties into .tres files.
## It is not here for Inspector editing — all item data is authored in [code]items.json[/code]
## and generated by [code]generate_item_resources.gd[/code]. Do not add @export_group or
## reorganize for Inspector readability; the Inspector is not the authoring surface.

## Unique identifier used for lookups.
@export var id: StringName = &""

## Determines item type.
@export var type: Type = Type.MED

## Display name shown in UI.
@export var ui_name: String = ""

## Display description shown in UI.
@export var description: String = ""

## Grid size this item occupies in the inventory.
@export var inventory_size: Vector2i = Vector2i(1, 1)

## Price to purchase this item from the merchant. [code]0[/code] means not buyable.
@export var buy_price: int = 0

## Price received when selling this item to the merchant. [code]0[/code] means not sellable.
@export var sell_price: int = 0

## Maximum number of this item that can occupy a single inventory slot.
## [code]1[/code] means not stackable.
@export var stack_size: int = 1

## Earliest chapter in which this item becomes available in the merchant shop.
## Only meaningful when [member buy_price] is non-zero.
## [br][br]
## Non-shop items ([member buy_price] == [code]0[/code]) are assigned
## [constant ItemSchema.AVAILABILITY_NOT_FOR_SALE] by [code]generate_item_resources.gd[/code].
## This sentinel exceeds [constant ItemSchema.MAX_CHAPTER], so [code]availability <= chapter[/code]
## is always [code]false[/code] for them — a [member buy_price] guard is not needed.
@export var availability: int = ItemSchema.AVAILABILITY_NOT_FOR_SALE

## Ammo type this weapon consumes. Only meaningful when [member type] is [constant Type.WEAPON].
@export var ammo_type: AmmoType = AmmoType.NONE
