# Autoload cannot have class_name, read "res://docs/godot/can_autoload_have_class_name.md"
# This is the ItemRegistry autoload
extends Node
## Static catalog of all ItemData resources.
##
## Loads every [code].tres[/code] resource from [constant _ITEMS_DIR] on startup
## and exposes them for lookup.
##
## This autoload holds no runtime state — use [code]PlayerInventory[/code] for
## inventory instances and [code]GameState[/code] for progression state.
##
## Blueprints are generated [code].tres[/code] files produced by running
## [code]src/editor/generate_item_resources.gd[/code] whenever
## [code]src/resources/data/items.json[/code] changes.

const _ITEMS_DIR: String = "res://src/resources/data/generated/items/"

## Dictionary mapping [StringName] id to [ItemData].
var _items: Dictionary[StringName, ItemData] = {}


func _ready() -> void:
	Utils.require(
		DirAccess.open(_ITEMS_DIR) != null,
		(
			"ItemRegistry: items directory not found at '%s'. Run generate_item_resources.gd first."
			% _ITEMS_DIR
		)
	)

	for file_name: String in DirAccess.get_files_at(_ITEMS_DIR):
		# .uid sidecar files have extension "uid", so this correctly excludes them.
		if file_name.get_extension() == "tres":
			_load_item(_ITEMS_DIR + file_name)
	Utils.require(
		_items.size() > 0,
		(
			"ItemRegistry: no items loaded from '%s'. Run generate_item_resources.gd first."
			% _ITEMS_DIR
		)
	)


## Returns all items in the catalog.
##
## Order reflects dictionary insertion order, which matches the filesystem
## order returned by [method DirAccess.get_files_at]. This order is not
## guaranteed and varies by platform. No caller in this project requires a
## specific display order, so no explicit sort is applied. If a future caller
## needs ordering, sort at the call site.
##
## [b]INTENTIONAL DO NOT MARK THIS AS AN ISSUE[/b] — non-deterministic ordering
## is an accepted design constraint. The shop has no required display order.
func get_all_items() -> Array[ItemData]:
	# assign() converts the untyped Array returned by values() into a typed
	# Array[ItemData], which is not guaranteed by a bare return in all Godot 4.x
	# versions. Without it, the typed return annotation silently passes an
	# untyped array to callers.
	var result: Array[ItemData] = []
	result.assign(_items.values())
	return result


## Returns the [ItemData] for the given [param id].
##
## A missing id is an unrecoverable programmer error — callers should only
## request ids known to exist in the item database. [method Utils.require]
## Crashes via [method OS.crash] on an unknown id. This function never silently
## returns [code]null[/code]; a missing id always terminates the process.
func get_item(id: StringName) -> ItemData:
	var item: ItemData = _items.get(id, null)
	Utils.require(item != null, "ItemRegistry.get_item: unknown id '%s'" % id)
	return item


## Asserts that [param id] exists in the catalog.
##
## Crashes via [method OS.crash] (both debug and release) if the id is unknown.
## Use this when the caller only needs to confirm an id is valid and does not need
## the [ItemData] return value — it makes the intent explicit instead of calling
## [method get_item] and discarding the result.
func validate_item_id(id: StringName) -> void:
	Utils.require(_items.has(id), "ItemRegistry.validate_item_id: unknown id '%s'" % id)


func _load_item(path: String) -> void:
	var data: ItemData = load(path) as ItemData
	# These .tres files are generated by generate_item_resources.gd, which validates
	# every entry before writing any file. A bad resource here means either a
	# hand-edited .tres or a generation bug — neither has a recovery path.
	Utils.require(data != null, "ItemRegistry: file at '%s' is not an ItemData resource." % path)
	Utils.require(not data.id.is_empty(), "ItemRegistry: resource at '%s' has an empty id." % path)
	Utils.require(
		not _items.has(data.id), "ItemRegistry: duplicate id '%s' in '%s'." % [data.id, path]
	)
	# -------------------------------------------------------------------------
	# INTENTIONAL DO NOT MARK THIS AS AN ISSUE :
	# ammo_type is NOT validated here and never will be.
	#
	# This has been flagged as a gap in multiple reviews. It is not a gap.
	#
	# Weapons can have ammo_type = NONE — that is a valid state for infinite-ammo
	# weapons (e.g. melee, unlimited firearms). Because NONE is a legal value for
	# weapon items, the inverse rule ("non-weapons must have ammo_type == NONE")
	# cannot be enforced by simply checking the field value alone at runtime.
	#
	# The static pipeline (generate_item_resources.gd) owns this validation: it
	# checks every JSON entry before writing any .tres file and rejects the entire
	# batch on any violation. Runtime re-validation here would duplicate that rule,
	# create a second place to keep in sync, and provide no meaningful safety gain —
	# a hand-edited .tres would break far more than just ammo_type.
	#
	# Do not add ammo_type validation to this function.
	# See docs/decisions/item_architecture.md — "Static data pipeline" section.
	# -------------------------------------------------------------------------
	_items[data.id] = data
